#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#    Mar 27, 2020 08:02:15 PM IST  platform: Windows NT

import sys
from bs4 import BeautifulSoup
import requests

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import CV_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    CV_support.set_Tk_var()
    top = Toplevel1 (root)
    CV_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    CV_support.set_Tk_var()
    top = Toplevel1 (w)
    CV_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:


    def escape(self,event):
        self.Listbox1.delete('0','end')
        self.TCombobox1.delete('0','end')


    def result(self):


        ac=self.TCombobox1.get()
        self.escape(self)
        if ac=='World':
            v='https://www.worldometers.info/coronavirus/'
            l=''
        else:
            l = ''
            v = 'https://www.worldometers.info/coronavirus/country/'
            v = v + ac
        res = requests.get(v)
        soup =BeautifulSoup(res.text, 'lxml')
        for i in soup.select('.maincounter-number'):
            l = l + i.text
        z = l.split()
        a, b, c = z[0], z[1], z[2]
        a, b, c = int(a.replace(',', '')), int(b.replace(',', '')), int(c.replace(',', ''))

        ba = (int(b) / int(a) * 100)
        ca = (int(c) / int(a) * 100)

        self.Listbox1.insert(1,' '*20+ac)


        self.Listbox1.insert(1,'  Death % : '+ str(round(ba, 2)))
        self.Listbox1.insert(1,'  Recovered % : '+ str(round(ca, 2)))
        self.Listbox1.insert(1, '  Deaths : ' + str(b))
        self.Listbox1.insert(1, '  Recovered : ' + str(c))
        self.Listbox1.insert(1, '  Cases : ' + str(a))


    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("395x282+691+150")
        top.title("CV19")
        top.configure(background="#601DA2")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.127, rely=0.106, height=26, width=272)
        self.Label1.configure(background="#FDFEFE")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#17202A")
        self.Label1.configure(text='''COVID19''')
        self.Label1.configure(width=272)

        self.TCombobox1 = ttk.Combobox(top)
        self.TCombobox1.place(relx=0.203, rely=0.284, relheight=0.092
                , relwidth=0.473)
        self.TCombobox1.configure(textvariable=CV_support.combobox)
        self.TCombobox1.configure(takefocus="")
        self.TCombobox1.bind('<Escape>', self.escape)
        self.TCombobox1['values']=('World',
                          'India',
                          'us','China',
                          'Italy','South-korea',
                          'France',
                          'Germany',
                          'Spain',
                          'uk',
                          'Belgium',
                          'Australia',
                          'Portugal','Brazil','Canada','Turkey')


        self.TCombobox1.current(0)



        self.TButton1 = ttk.Button(top)
        self.TButton1.place(relx=0.734, rely=0.284, height=30, width=98)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(command=self.result)
        self.TButton1.configure(text='''GO''')

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.0, rely=0.461, relheight=0.525
                , relwidth=1.023)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font=font10)
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(width=404)

if __name__ == '__main__':
    vp_start_gui()





